### ISSUE TITLE
Create README outlining approach/roadmap

### ISSUE THREAD

**Issue by nadinengland** [overengineering/rustassonne#1]
Rather than requiring a discussion each time we start we should have a README that outlines the general roadmap for the project. Perhaps it can be as simile as system architecture at the minute? It will obviously change over time but would be good to start with something. 

Should also include link to rules we are implementing (I believe these are them): http://www.fwtwr.com/fwtwr/carcassonne/rules.asp

**Comment by nadinengland** [comment]
Should also include link to the rules of Carcassonne that we are implementing.

**Comment by StefanoChiodino** [comment]
@nadinengland please check readme and close if happy

**Comment by nadinengland** [comment]
Both 2800724cf88843135978209d66becbd2de3c4d31 & 24357a721ed18b9d3614b9336ed77a7534fe054c resolve this 👍
