### ISSUE TITLE
Add `Field` to `Feature`s

### ISSUE THREAD

**Issue by nadinengland** [overengineering/rustassonne#3]
Previously, we discussed how the `Field` [Feature][1] could be implemented as the absence of any feature. However, I believe this will add unnecessary complexity to the logic later on as a tile can have multiple `Fields`. E.g. as seem in the [straight road tile][2].

Instead a `Field` value should be added for the `Feature` enum which also has a `connection: Vec<Direction>`.

[1]: https://github.com/overengineering/rustassonne/blob/master/src/models/feature.rs
[2]: http://www.fwtwr.com/fwtwr/carcassonne/images/rules_17.gif

**Comment by LeeARichardson** [comment]
Add central road Terminal feature.

**Comment by nadinengland** [comment]
Fixed in #11
