### ISSUE TITLE
Implement all cardinal directions

### ISSUE THREAD

**Issue by nadinengland** [overengineering/rustassonne#4]
The [Directions][1] model will need to represent all 16 cardinal directions of what is called a [16-wind compass rose][2]. I know we discussed not adding them until needing them, but I'm creating this for posterity. 

- North
- NorthNorthEast
- NorthEast
- NorthEastEast
- East
- etc.

[1]: https://github.com/overengineering/rustassonne/blob/master/src/models/direction.rs
[2]: https://en.wikipedia.org/wiki/Points_of_the_compass#16-wind_compass_rose

**Comment by nadinengland** [comment]
After documenting Issue #5, it became apparent that all 16 directions aren't necessary, or rather I don't believe will be needed in the path finding logic later on. Specifically, the corners aren't needed:

- NorthEast
- SouthEast
- SouthWest
- NorthWest

As far as I can tell, none of the came rules seem to car about matching at direct corners, but instead the edges either side, e.g. NorthNorthEast to SouthSouthEast.

**Comment by StefanoChiodino** [comment]
> [I'm creating this for posterity.](https://2.bp.blogspot.com/-i2GVWy6dnbE/UMpXAAA85kI/AAAAAAAAD78/h-MhbE-eQgE/s1600/stephen-colbert-told-you-so.gif)

I think in reality we MAY need 12 directions, I don't think 8 would be enough as in [this case](http://www.fwtwr.com/fwtwr/carcassonne/images/rules_05.gif) NorthEast is both `City` and `Field`

**Comment by nadinengland** [comment]
Exactly, its appears better to describe them by the double directions in that case, `City` is `NorthNorthEast` and `Field` is `NorthEastEast`. Easy enough to extend if we realise it is necessary.

**Comment by LeeARichardson** [comment]
12 directions, discerned by Top, Right, Bottom, Middle, then Left or Right.
E.g. TopLeft, Top, TopRight, RightTop, Right, RightBottom, etc.

**Comment by LeeARichardson** [comment]
#10
