### ISSUE TITLE
Connections on Features should be a set not a vector

### ISSUE THREAD

**Issue by nadinengland** [overengineering/rustassonne#6]
After documenting Issue #5 it seemed sensible to change the `connections: Vec<direction>` to a Set, presumably a [HashSet][1]. This is because a `Feature` only every touches a direction once. Future expansions may bring rule changes (e.g. a road that loops back on itself in one tile?) but let's not pre-optimise for this.

[1]: https://doc.rust-lang.org/std/collections/struct.HashSet.html

**Comment by StefanoChiodino** [comment]
> but let's not pre-optimise for this.

@nadinengland that sounds like under-engineering. You have been warned.
